package gomez_tp6;

/**
 *
 * @author jon gomez
 */
public class Menu extends javax.swing.JFrame {
    
    private static Directorio dir = new Directorio();

    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmenuAgregarClientes = new javax.swing.JMenuItem();
        jmenuBuscarCliente = new javax.swing.JMenuItem();
        jmenuBorrarCliente = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jEscritorio.setPreferredSize(new java.awt.Dimension(460, 360));

        javax.swing.GroupLayout jEscritorioLayout = new javax.swing.GroupLayout(jEscritorio);
        jEscritorio.setLayout(jEscritorioLayout);
        jEscritorioLayout.setHorizontalGroup(
            jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        jEscritorioLayout.setVerticalGroup(
            jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        jMenu1.setText("Clientes");

        jmenuAgregarClientes.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jmenuAgregarClientes.setText("Agregar Cliente");
        jmenuAgregarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuAgregarClientesActionPerformed(evt);
            }
        });
        jMenu1.add(jmenuAgregarClientes);

        jmenuBuscarCliente.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jmenuBuscarCliente.setText("Buscar Cliente");
        jmenuBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuBuscarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jmenuBuscarCliente);

        jmenuBorrarCliente.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jmenuBorrarCliente.setText("Borrar Cliente");
        jmenuBorrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuBorrarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jmenuBorrarCliente);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Salir");

        jmSalir.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jmSalir.setText("Cerrar ventana");
        jmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSalirActionPerformed(evt);
            }
        });
        jMenu3.add(jmSalir);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmenuAgregarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuAgregarClientesActionPerformed
        // TODO add your handling code here:
        jEscritorio.removeAll();
        jEscritorio.repaint();
        vistaAgregarClientes vac = new vistaAgregarClientes();
        vac.setVisible(true);
        jEscritorio.add(vac);
    }//GEN-LAST:event_jmenuAgregarClientesActionPerformed

    private void jmenuBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuBuscarClienteActionPerformed
        // TODO add your handling code here:
        jEscritorio.removeAll();
        jEscritorio.repaint();
        vistaBuscarCliente vbc = new vistaBuscarCliente();
        vbc.setVisible(true);
        jEscritorio.add(vbc);
    }//GEN-LAST:event_jmenuBuscarClienteActionPerformed

    private void jmenuBorrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuBorrarClienteActionPerformed
        // TODO add your handling code here:
        jEscritorio.removeAll();
        jEscritorio.repaint();
        vistaBorrarCliente vbc = new vistaBorrarCliente();
        vbc.setVisible(true);
        jEscritorio.add(vbc);
    }//GEN-LAST:event_jmenuBorrarClienteActionPerformed

    private void jmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jmSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    
    public static Directorio getDirectorio(){
        return dir;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jEscritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmSalir;
    private javax.swing.JMenuItem jmenuAgregarClientes;
    private javax.swing.JMenuItem jmenuBorrarCliente;
    private javax.swing.JMenuItem jmenuBuscarCliente;
    // End of variables declaration//GEN-END:variables
}
